# permissions for end users to view aics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: aic-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: aic-operator
    app.kubernetes.io/part-of: aic-operator
    app.kubernetes.io/managed-by: kustomize
  name: aic-viewer-role
rules:
- apiGroups:
  - aic.quicinc.com
  resources:
  - aics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aic.quicinc.com
  resources:
  - aics/status
  verbs:
  - get
