apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: AI/Machine Learning, OpenShift Optional
    certified: "false"
    containerImage: ghcr.io/quic/cloud_ai_openshift_operator:test1
    description: Automate the management of OpenShift Operator for Qualcomm AI 100
      accelerators.
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "false"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    provider: Qualcomm Innovation Center, Inc.
    repository: https://github.com/quic/aic-operator
    support: Qualcomm Innovation Center, Inc.
  name: aic-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AIC is the Schema for the aics API
      displayName: AIC
      kind: AIC
      name: aics.aic.quicinc.com
      version: v1
  description: The Openshift Operator enables the Qualcomm® Cloud AI series of hardware
    on OpenShift clusters by automating the configuration and installation of their
    Linux device drivers and its Kubernetes Device Plugin.
  displayName: AIC Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAkFBMVEX///8yVNwvUtwsUNsYRdr19/0cR9oqT9sTQ9onTdsiStskS9tZcuEeSNoRQtrS2Pbc4fjJ0PS5wvH4+f7k6PpieeLx8/yst++0vvCnsu7t8Pzh5fnp7Ps3WN3CyvOksO1HZN98juZTbeBnfeNtguSQn+pAX96JmejW2/d2ieWdquxLZ9+Ck+eUoupDYd5/kedMvY3nAAALrUlEQVR4nO1da1ciPQze6ZS5MsNNLiKggqIC6v//d6+XdVeQPG3Tdsq+h+fTnrPH6YRp0iRNnvz6dcYZZ5xxxhlnnHHGGWecccYZZ5xxxj5G09nFVbd7dTFrhX4Vpxhc9Mb3T+15UtdZlsk3ZFld5+vh7fOkNw39drbojm9f0iwp8jQWIvoOIeI8r6SMlg+Tx0Ho92Rh1HtuS1nkB5L9QJwXMlve9/6xjTsbtxNZKmT7LmaZVMPxLPRr6+Jis62LWFu6r20bF/Xy8h/Qy9Zkm+XG4n19yiJr909bKTtPifnX2xcySXfd0GKQmMyzXF/3SOR1uxdalKMYzxMH4n0gli/90OL8wDgtXMn3IWMyn4QWaQ/9eeVQvA+IZH4637FzI11+vz8yyuVp2JzpXWZnPmnE2e0JuDrjJPUk3zvyPPRWvdg6M6AEZDuon3MpfW3Qv0ircFa1NfRiYQ4h5CqQNnbSvAH53pGmQZycTd3EB/yEqDfNCzhMGpPvHfKuYflGL03t0C+U60Ztajf1b0MPEedXzQnY4dpQ8YmI9eci6TQl4KI2FiwtK5kVYr5+2d5s11EuZVWax5J1Qw7OxMiIxnlVJ+3d9eJxOvpKUAxao+7icteWWWWU8RB1I4f/WP8LirRKls8LOoc2WzxsZZHq/2L15SkJmCbV00LtjUwnd5W+9+5fxImugGW2Wmg/dbGqS10RPW/Unp6AcSI2ZsfXdBMleipZ6/9wDDxmOioTyy3H6PVftA4hkXk8NKZawWByw/WTF+tKYwGR+PNuXjT2UZnaKMploeENxi/OJDrASm0NYnlvt8bgVSPrU67cCHSIa6lculjb+47ddaFcR3oJpjpKMyqyZycr3audptpDSNxSeh5p5MrIdVKlB5COHK31FyuVCaiG7u7FWkvVTk3bzhb7jUmmWFI+OF3vVqX00rH7pjwJnfuLG4XaC+n2UryNFUNk7r3FicJ/ipdOV8N7RnjxFRcKkyrH7tZqKaxM5scZXmDdF4U7e3qLJfQW0ChCtdRZhrGLF5LXrhb6gUusHbWrA3gJ9aHYOVrmGHbwbjm+cbNKH/6Q+dDNKgSwoyHd6MccfcJ47mQNEoM5CjVE5GKNCbygyHxftXfhsVi4cDRggtq173QEY6gkqb0z3Eef0L3/ewRDpIqF/bF/A/RAFE3cB42QhPaa2EF7xKXfBNBHvo31Lf8QuNxufV/mS4i13bNnyJ3xbkf/vAXcSHYJjXuQXktvHQmgxgNQxdQu8YaO26y5a+cWyhRLm/dYgO1Ruk1bYGzAXipsPP87WsVF4j7bRWMACv9tbE0L2JncZ0jxE8/gI9Z8izcBOb2s2e4IpIklPxE9pA2Nu/haEzvanPK36Qj8brKxyo/f6ALHJuPelvTpAFt4DguPYEtvqJJrTUECqmy+kg4YBbb7CDZpw3bmHS2Qdq95BahX9M6Pm4gLDwEO54qXsB3T28JB3GkOYBZynn8FfrM6RKsg8D/iLeuJdI7NNiZjok1b04SjiDNaDXPLcgQmrmnPjXU8L+htbxl0ctGlI52Sk/N7pk/Dqsmw4hvo4yJ/YjxuRe56pl7bg/aTWZaBVmumbbYHiIMT88zwiN70Rag2nR6dnZbmzjdQaxmqLRCY98TcqwGmtPbw8nqgXVPGFc0l6bMFiJy+sCSNA8M20CnK2FNloAZeyZdi5Bxor7ThHNR30MaUESLSTiA7orZHn1Yd8wPxhVbqcK259HEhcuOHUY96M8zhOB3AEZYZH/ngcA3XJT+lJaxNby8GdLgZIEfzhRGddsguTJ9FS+ixGUAFUKhsvLOAg1QGip3eMAAp6kfDZ12QEoqAEgL7ZxzlAwnzgBLOaQlNLTy9S4N+Qzo7ZizhlNZDh4WrxgDf0HSXnqYtRXpoamnAeWhVGWCHQezutBjQu9T4bHWHFt3/be5pgWeZ7gd3mNK+pHntC221Anre9BnG8LzpK9eA0RNdRyhS44eBCDgAk8pv0BdsjAj4JLMYly6zGPenmInakT87IxNF3wAHzCbSFxeMC7+TzAjT4SHj3v0Us/rIlTTP6qObmVDHBSg6Z9zMACc32O0auOZOGI8DN6RNVbAfgj7BWDekdEWnKAJx4IFtxak5R5UKdoWJvYdhex/DnY6hAEVarP4nVG1iw50wWGZ5LPYR5zJVywiKtHjxDh1dWJUqEG1MGixXQA0rVoMXqvrip2rIHhVRqyJrUPXFs330LbBNrQJ9pqlcS1CnwCzSAnXHMb81FpgLxeUKKOjlBuWozJu/Tem9jwPPAeDo43rKT/TLWBSY0kX3OGhZ0JuUXdALSlYtrCnY/DBvDVoj2N3AI9AMb9GZR2eAkK0Bx7NFfhN1lLxyH4oObnAKgT5Biw0F3sWisavFcb6QnbFIjYGI0+axtAWjaSDA4RzVFgRjdAQViZzdCQ8CWVK9QYellQ8JLHRU8D/imnxfKlM5BkbPrjUCNVGz6uM/QBdviez4X4BPKOxqslGLMT+ZMaX1uzqaA0JaaNkniLvVPRxDR90T1CYY2ZJ9giMxStn+N+igPvazge7KSNgSYfZQs3/GTivSzzySP4CMjfazISBnacw1NsBD+XlNRpved9iJ90vBoZRztfwClAkcut8PiEPRBQUPJFFiM7XR7FqHthGTMztg4MEsSqJiFipO6CN8/0a+BQcoWvEp/AFUAy6nL/Ck99+6Dcm+zO+2jwGT+5VMhhP6snMvQ/8MCdsSR72sdJfDO5iUe4DI71tKHfMKOiOFfsSsgsxTkSag+kt808PckO7YhDEzpOAtBK7R5W8DCW5pP34Jd3R/kG0rYt7UjEAT06efcoVntYrEYcE5ZoVjer8g1F9qCBhVTut6FCy7kWSc/MDlfb+z7ioEdMw9P1WMLWDNR6G9pfJePa3HNdOYap9GtfnlCAj1I+WkkMoN//s3IFa4DyTGXjgI9YWKsdxDt7Wadb40HhuAwmsFKg+FyuoBLLEp1yciS8PwM4plo3wfYTpwkitg5Ym2QmOCR2oWziDSQrSKN3qctVpvRDU32EBXpvPNPhDPvU0nn+rMbX7bqvonFQ5bCDieGbCHrta8ojgb6vriINSnIJzxlB+F7kQruR5rpeHQpRkB3wP0dKeSiaJ41fmtX03nJdfeKaq0B6+JVIp7pZCKEPCngCc1PC+KcilWl4/A8s36ZvNM60a4AMwmPKaFrG+envud2Z5itmad/vMqr9WznfYEbOALvqNvOglYpHkhszyab5ftYXt5s55HeSarnO5EO/6YZkZYvmPBmrQqIhF/gDlrVXgahXIUIabliqTRnrnRDc+j5CNfN0108MSOfFhI/A4KOYrrBiePR7XznIUOOrGpP8JFmgdq6mytuNOrjSDkMFx//KX0b1ONcyNuMVtqDV+1QLkNRxbzibE08ywNEbBh9Q9Gt1pDgpmwqJl3iMetR4vjM2VhgMXamzoG7Bzfx0T4klGEFu0P+ms/R0cgSt+jWGwz88SSEiwCXW/o7nLNGfD6aHYYihqD/lDq5I0NEIQAHmJ63a4L5V3cj09F/k8wYmaE0eQul6V2GkakpQTla41NzjLDoLMZVlmRK9RSxHmVlavrLqD8CUQBr4Wr/sMyymSRp/HBNxIizctCyvnwuf9Z90xTjTiqz/OHaae/2a3WZV3X2Sfe/pXfrHabfuebmUQ9bQ0m2awwGE1nF1cXs+lx80/3tJ2G+20P1IwekCLOIQZ0hHIy7rcl6BLIQCNDnAP1tDU9QMsT6EI3FrPHCYLmnxGlt/KLRgEoRe2bf04DK7qAPxTrj2OAnlUlL8g/AjDLLsjdjHugQrfQ7+YGgPnklDJSNgA9beHoGp0CzHG0IDY6KdD1SC6aKU8BdKEbTSnxb+ERUAWfZkbKGPT4l/QE7hJd4JruaatCv5sbAMqYxscsewLNhBdspJ1j0BQKDKLZ08QTUd4uskCsou5xV8c/bmpEFDdXXuofvWGUV8V3VGU0/J/YmS+0DsF90H+zrK/aiO81jgAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - AIC
  - AIC-Operator
  links:
  - name: AIC Operator
    url: https://github.com/quic/aic-operator
  maintainers:
  - email: quic_vmellemp@quicinc.com
    name: quic_vmellemp
  - email: quic_carls@quicinc.com
    name: quic_carls
  maturity: alpha
  provider:
    name: Qualcomm Innovation Center, Inc.
    url: https://github.com/quic/aic-operator
  version: 0.0.0
